config/routes.rb
SteamTruckApp::Application.routes.draw do

  resources :users do 
    member do 
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :projects
  root "static_pages#home"
  match '/signup',        to: 'users#new',              via: 'get'
  match '/projects',      to: 'projects#index',         via: 'get'
  match 'projects/new',   to: 'projects#new',           via: 'get'
  match '/signin',        to: 'sessions#new',           via: 'get'
  match '/signout',       to: 'sessions#destroy',       via: 'delete'
  match '/help',          to: 'static_pages#help',      via: 'get'
  match '/about',         to: 'static_pages#about',     via: 'get'
  match '/contact',       to: 'static_pages#contact',   via: 'get'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :project_title, presence: true, length: { maximum: 90 }
	validates :description, presence: true, length: { maximum: 800 }
	validates :problem, presence: true, length: { maximum: 300 }
	validates :solution, presence: true, length: { maximum: 300 }
	validates :status, presence: true, length: { maximum: 100 }
	validates :user_id, presence: true
	mount_uploader :image, PicUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

	def new
		@project = Project.new
	end

	def index
		@projects = Project.all
		@project = current_user.projects.build if signed_in?
	end

	def show 
    @project = Project.find(params[:id])
	end

	def create
  		@project = current_user.projects.build(project_params)
  		if @project.save
  			flash[:success] = "Project created!"
  			redirect_to @project
  		else
  			render 'new'
  		end
  	end 

  	def edit 
  	end

  	def update
    	if @project.update_attributes(project_params)
      		flash[:success] = "Project updated!"
      		redirect_to @project
    	else
      		render 'edit'
    	end
  	end

  	def destroy
    	Project.find(params[:id]).destroy
    	flash[:success] = "Project deleted."
    	redirect_to(index_path)
  	end

  	private

  		def project_params
  		params.require(:project).permit(:project_title,:description, :problem, :solution, 
  										:status, :image) 
  		end

      def correct_user
        @project = current_user.projects.find_by(id: params[:id])
        redirect_to root_url if @project.nil?
      end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<% @projects.each do |project| %>
<li>
	<ul>
		<li><%= project %>
	</ul>	
</li>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>

<h1>Edit Project</h1>
<body id="home">
	<div class="hero-unit">
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@project) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>
					<div class="field">
						<%= f.text_area :project_title, placeholder: "New title..." %>
						<%= f.text_area :description, placeholder: "New description..." %>
						<%= f.text_area :problem, placeholder: "New problem..." %>
						<%= f.text_area :solution, placeholder: "New solution...." %>
						<%= f.text_area :status, placeholder: "Update status..." %>
						<%= f.file_field :image %>

					</div>
					<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<h1>Projects</h1>
<body id="home">
<div class="hero-unit">
<% @projects.each do |project| %>
	<ul>	
			<li><%= link_to "#{project.project_title}", project %> | <%= project.description %> | <%= time_ago_in_words(project.created_at) %> ago</li> 

	</ul>
<% end %>
</div>
<%= link_to "New Project", new_project_path, class: "btn btn-large btn-primary" %>
</body>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>

<h1>New Project</h1>
<body id="home">
	<div class="hero-unit">
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@project) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>
					<div class="field">
						<%= f.text_area :project_title, placeholder: "Add title..." %>
						<%= f.text_area :description, placeholder: "Add description..." %>
						<%= f.text_area :problem, placeholder: "Add problem..." %>
						<%= f.text_area :solution, placeholder: "Add solution...." %>
						<%= f.text_area :status, placeholder: "Current status..." %>
						<%= f.file_field :image %>
					</div>
					<%= f.submit "Start Project", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/projects/show.html.erb
<% provide(:title, "#{@project.project_title}") %>
<h1><%= @project.project_title %></h1>
<body id="home">
<div class="row">
		
	<div class="hero-unit center">
		<p>
		<%= image_tag @project.image_url.to_s %>
		</p>
		<h2>Description: </h2>
		<p><%= @project.description %></p>

	</div> 
	<div class="hero-unit">
		<p><strong>Problem:</strong><br><%= @project.problem %></p>
		<p><strong>Solution:</strong><br><%= @project.solution %></p>
		<p><strong>Status:</strong><br><%= @project.status %></p>
	</div>

	<%= link_to "Edit Project", edit_project_path, class: "btn btn-large btn-primary" %>
</div>
</body>